alias "so"="source ~/.zshrc"
alias "vim"="nvim"
alias "icat"="kitty +kitten icat"
alias "zathura_tabbed"="nohup tabbed -c zathura -e >> /dev/null 2>&1 &"
alias "yt-dlpmp4"="yt-dlp --format='best/mp4'"
alias "pf"="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias "pc"="proxychains4"
alias "open"="xdg-open"
alias "vpn"="rlwrap /opt/cisco/anyconnect/bin/vpn"
alias "vpnconnect"="/opt/cisco/anyconnect/bin/vpn -s < /home/xtayex/Documents/vpn/connect.txt"
alias "vpndisconnect"="/opt/cisco/anyconnect/bin/vpn -s < /home/xtayex/Documents/vpn/disconnect.txt"
alias "restartxmonad"="pkill stalonetray; pkill xmobar; xmonad --recompile; xmonad --restart"
alias "hexo"="$HOME/Documents/My_Blog/blog/node_modules/hexo/bin/hexo"
alias "hoogle"="stack hoogle"
alias "ls"="lsd"
alias "kssh"="kitty +kitten ssh"
